services:
  - docker


  script:
  - docker build . -t martensjostrand/pizza:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push martensjostrand/pizza:latest

