language: golang
services:
- docker
script:
- docker build . -t martensjostrand/pizza:latest
- echo "$DOCKER_PASSWORD" | docker login -u martensjostrand --password-stdin
- docker push martensjostrand/pizza:latest
env:
  global:
    secure: rS+t/RfBs4jNhp0fwyM+NrzI/suoFVF9d3v1PemfEhiMdLkXX1zIE0mQaEa/77bbm4dvjE+QmRywR1/uEB6YUeBDCTYVkx3QsAtoU44nbNF7BZD2NUuIWdYwFnBqhbM01HIcXSLuMpHV726CE1CHt/wUAkp3dEyRIRHsRpIcqwtOOufd8fs3PUNgvdblSUNYIFgMrSQW3ddj7SY7pLfGOcTdBDEJz2BjBKbYRmk39jAZ0/l5ME+oAb71wt5CFbfPOWSDY5n3RlTJ5ZPRuDQ9c6k6iuXtlbrHoy2KsDNZ7tRnwIypPQZFSS9WBfS1JmVDWCBf9alvnwFXJ+pQi2ahpNbqGiV5Kiu1IEjb7qdk1UTRCHZ+6GT3seK8fxO4dhJX+6La2mZDgDaxWVBLFZStog2WPFB9ts1m4GHQ8gXIBJPS3bcqIjz1CH1lznZOeKtOte+iu3o7jO8I7Hh7Z8pJGVQMEv51266VBfAxJhwqm+lRO+XjElC5cmJ2dSniDJVMUla/TASAttFZ5LWJuws/mCbtz01dnn+bfcJD06Jetmqu8LcXlnfIJVgyWJC2NzmFPZ/zTg7qgpIWgTWwuFfHBeH5r/w9P18F8FhK6s/GwixyCqv8WOQdLmY1MBbrsrqBxU2lBO64WZxB1Podg0011oWmvzMbbvWeth5do9XKPqA=
